name: sprintf
version: 7.0.0
description: Dart implementation of sprintf. Provides simple printf like
  formatting such as sprintf("hello %s", ["world"]);
homepage: https://github.com/Naddiseo/dart-sprintf

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  lints: ^1.0.1
