name: sprintf
version: 3.0.2
author: Richard Eames <dartsprintf@naddiseo.ca>
description: Dart implementation of sprintf
homepage: https://github.com/Naddiseo/dart-sprintf
dev_dependencies:
  test: any
